[test]
# Test configuration
preload = ["./test/setup.ts"]
timeout = 30000
coverage = true
coverageDir = "coverage"

[install]
# Install configuration
cache = true
production = false
frozenLockfile = true
